/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tech_smallwonder_libmediafy_MediaPlayer */

#ifndef _Included_tech_smallwonder_libmediafy_MediaPlayer
#define _Included_tech_smallwonder_libmediafy_MediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    newPlayer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_newPlayer
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    setDataSource
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_setDataSource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    hasMedia
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_hasMedia
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    play
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_play
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_pause
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_stop
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    isPlaying
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_isPlaying
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    getEqualizerBands
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_getEqualizerBands
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    enableEqualizer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_enableEqualizer
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    disableEqualizer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_disableEqualizer
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    isEqualizerEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_isEqualizerEnabled
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    getEqualizerFrequency
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_getEqualizerFrequency
  (JNIEnv *, jobject, jint);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    setEqualizerFrequency
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_setEqualizerFrequency
  (JNIEnv *, jobject, jint);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    getNumEqualizerPresets
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_getNumEqualizerPresets
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    getEqualizerPresetName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_getEqualizerPresetName
  (JNIEnv *, jobject, jint);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    getEqualizerPresetFrequency
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_getEqualizerPresetFrequency
  (JNIEnv *, jobject, jint);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    getPreamp
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_getPreamp
  (JNIEnv *, jobject);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    setPreamp
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_setPreamp
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     tech_smallwonder_libmediafy_MediaPlayer
 * Method:    setEqualizerPreset
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_tech_smallwonder_libmediafy_MediaPlayer_setEqualizerPreset
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
